### ISSUE TITLE
Reduce bottom padding on Tomate title

### ISSUE THREAD

**Issue by rayhogan** [rayhogan/tomate#21]
Compare the "T🍅️mate" title in the Readme screenshot to what is live on: https://rayhogan.github.io/tomate/

There is currently too much bottom padding. Reduce it so it is closer to what is in the readme.

**Comment by vilasrhegde** [comment]
@rayhogan shall I solve this one? I really got this one

**Comment by vilasrhegde** [comment]
@rayhogan check this one
![image](https://user-images.githubusercontent.com/85540091/194604051-12cad44d-2e89-4239-893a-aa445d7e06c0.png)

**Comment by rayhogan** [comment]
Looks good to me!

**Comment by vilasrhegde** [comment]
@rayhogan would you merge it? thanks

**Comment by rayhogan** [comment]
This issue is up for grabs again.

**Comment by manastelavane** [comment]
Hey, I would like to take this issue

**Comment by manastelavane** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/82931004/195091891-d9704a12-705f-46a6-ad86-86022567baa0.png">

FIne?

**Comment by rayhogan** [comment]
Yes looks great!
