### ISSUE TITLE
Bug: 'Break Time' timer still showing after Reset button clicked

### ISSUE THREAD

**Issue by rayhogan** [rayhogan/tomate#25]
**Reproduce**
Pause the timer during a break time. Click the reset button. Observe that the "Break Time" text and timer is still showing even though it is meant to change back to "Work Time".

**Solution**
There is a handler that resets the app.
```
resetSettings(e) {
    clearInterval(this.state.workInterval)
    clearInterval(this.state.breakInterval)
    this.setState({
      running: false,
      paused: false,
      workTimer: this.state.workTime * 60,
      breakTimer: this.state.breakTime * 60,
      backgroundColor: "#f9b08a",
    })
  }
```
This needs to be updated to include setting the state variable 'break' to false, as the style rule uses the 'break' state to determine which timer to show.
![image](https://user-images.githubusercontent.com/769565/194638589-f80d4b01-9b0d-4abe-ba63-9e30e305cf0d.png)

**Comment by Tejax-v2** [comment]
please assign me this issue
