### ISSUE TITLE
Inconsistency of Layout in Mobile View

### ISSUE THREAD

**Issue by S-ahil-Saxen-a** [rayhogan/tomate#35]
The sizes of the buttons and timer text are not consistent enough in the mobile view as the timer text of is too small to see.
Assign me to make a better mobile view experience and for better alignment under hacktoberfest 22

**Comment by rayhogan** [comment]
Can you provide some screenshots of what you're referring to?

**Comment by S-ahil-Saxen-a** [comment]
![image](https://user-images.githubusercontent.com/95903519/195185770-96a06e78-86fa-4b51-834b-130d1961d1e2.png)

1.) Timer text is too small to properly readable
2.) Buttons with respect to text or title are larger than it should be.
