### ISSUE TITLE
Add Alarm Clock Noise

### ISSUE THREAD

**Issue by rayhogan** [rayhogan/tomate#7]
As a User, I would like to hear an alarm clock noise, so I know when my break starts/ends

**Implementation**

Find a royalty-free alarm clock sound and play the sound a few seconds before the work time and the break time ends. This will allow the user to know that the state has changed if they have it in a browser tab that isn't visible.

There are many ways to play sounds in React. Here is a blog post that uses a library from npm: https://www.joshwcomeau.com/react/announcing-use-sound-react-hook/

In the PR, please show where you got the noise file so that appropriate credit can be given at the bottom of the readme.

**Comment by kala2** [comment]
Hey, can you assign to me please?

**Comment by rayhogan** [comment]
Sure! Excuse the code base for now -- it's a beginner-friendly hacktoberfest repo so there will be plenty of up-for-grabs type reformatting issues going up shortly. Happy hacking!

**Comment by kala2** [comment]
Hey @rayhogan, opened #11
