### ISSUE TITLE
Change Background Colour During Break

### ISSUE THREAD

**Issue by rayhogan** [rayhogan/tomate#9]
As a User, I would like the app background to change during a break, so I can easily see it is break time

**Problem**
The app's background is #f9b08a. It's not obvious (visually) when work time ends and break time starts.

**Implemention/Solution**
Change the background to a green colour (#86f490) during the break countdown and then revert it back during work time

**Comment by Dun-sin** [comment]
hi, can i try this?

**Comment by rayhogan** [comment]
Sure!
